### ISSUE TITLE
Dev Journey - 19.5.22

### ISSUE THREAD

**Issue by JeremyW1990** [JeremyW1990/dog-co#2]
**Task: create dummy data to mysql**

- [ ] Create two users in users table
- [ ] Create two dogs in dogs table
- [ ] Create a route , which connect to users together in routes table
- [ ] Write a tool scrip to generate a stream of [ latitude , longitude ] as dummy data of a routes
- [ ] Put the dummy stream of [ latitude , longitude ] data into geoLocations table
